id: AFA031CCC
base_file: fE93D.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:51:05.808941
  last_modified_at: 2022-06-19 17:51:05.808944
