id: AFA031CCC
base_file: fF3F5.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:51:05.812094
  last_modified_at: 2022-06-19 17:51:05.812097
