id: AFA031CCC
base_file: f4882.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:51:05.806249
  last_modified_at: 2022-06-19 17:51:05.806252
