id: AFA031CCC
base_file: f0234.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:51:05.799939
  last_modified_at: 2022-06-19 17:51:05.799946
