id: AFA031CCC
base_file: f04D2.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:51:05.802723
  last_modified_at: 2022-06-19 17:51:05.802726
