id: AFA031CCC
base_file: fC883.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:51:05.807886
  last_modified_at: 2022-06-19 17:51:05.807889
