id: AFA031CCC
base_file: f1F1E.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:51:05.803842
  last_modified_at: 2022-06-19 17:51:05.803845
